### ISSUE TITLE
训练代码问题

### ISSUE THREAD

**Issue by wwl629wwl** [iSEE-Laboratory/ASAG#1]
你好我想请问一下，To prevent users from confusing different ImageNet pretrained checkpoints, we require users to download the corresponding version of the checkpoint from [TorchVision](https://pytorch.org/vision/stable/models.html#table-of-all-available-classification-weights) manually. 是在那个torchvision里面下载相应的权重文件，还是在百度网盘中下载想要的checkpoint呢

**Comment by fushh** [comment]
Thanks for your interest. 
For training, you should download the pretrained backbone from [torchvision](https://download.pytorch.org/models/resnet50-0676ba61.pth). Otherwise, checkpoints provided by us are needed for evaluation.

**Comment by wwl629wwl** [comment]
谢谢 我再去试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iSEE-Laboratory/ASAG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月9日(星期六) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iSEE-Laboratory/ASAG] 训练代码问题 (Issue #1)





 
Thanks for your interest.
 For training, you should download the pertained backbone from torchvision. Otherwise, checkpoints provided by us are needed for evaluation.

**Comment by wwl629wwl** [comment]
您好，根据您提供的这个链接我下载了resnet50的model文件，如果我想要下载其他的model文件例如您readme文件中提供的链接https://pytorch.org/vision/stable/models.html#table-of-all-available-classification-weights 我该如何处理，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iSEE-Laboratory/ASAG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月9日(星期六) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iSEE-Laboratory/ASAG] 训练代码问题 (Issue #1)





 
Thanks for your interest.
 For training, you should download the pertained backbone from torchvision. Otherwise, checkpoints provided by us are needed for evaluation.

**Comment by fushh** [comment]
Taking AlexNet_Weights.IMAGENET1K_V1 as an example, you should first click the name, then click [SOURCE], and you can find the download url.

**Comment by wwl629wwl** [comment]
好的 再次感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iSEE-Laboratory/ASAG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月9日(星期六) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iSEE-Laboratory/ASAG] 训练代码问题 (Issue #1)





 
Taking AlexNet_Weights.IMAGENET1K_V1 as an example, you should first click the name, then click [SOURCE], and you can find the download url.
