### ISSUE TITLE
关于训练结果问题

### ISSUE THREAD

**Issue by hxl111111** [iSEE-Laboratory/ASAG#2]
我把代码跑起来了，但是因为是自己在算力云上跑的，只跑了一轮训练就去测试了，结果只有些精度。想问问测试的结果是有图片那种切割的结果的吗？

**Comment by hxl111111** [comment]
网上教的制作coco数据集的格式只有3个，你这个6个是咋做的啊而且我把我制作的用text打开和你的数据集也有点不同

**Comment by fushh** [comment]
During the training, the model will be evaluated for every epoch. Thus it is reasonable to evaluate the model at the end of epoch 1. We have provided all the training logs and you can compare with them.

As for the dataset, please follow the instructions in the README to prepare the COCO dataset. Just use the standard json annotations. No modification is needed.
