### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by HHX-688** [iSEE-Laboratory/ASAG#5]
File "E:\hhx\ASAG-main\ASAG-main\models\matcher.py", line 88, in <listcomp>
    indices = [linear_sum_assignment(c[i][valid_mask[i]]) for i, c in enumerate(C.split(sizes, -1))]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Code error

**Comment by fushh** [comment]
Thanks for your interest. However, I have tried to rerun the code and it runs successfully. If you still meet the device problem, you can add `.to(C.device)` to move the indices to the same device explicitly.
